{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "users_active_count{source=\"jwt-pizza-service\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Revenue/minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pizzaSales_total_revenue{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "CPU and memory usage percentage",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_load{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "system_memory_usage{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(auth_failed_auth{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failures"
    },
    {
     "expr": "rate(auth_successful_auth{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Sales/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "increase(pizzaSales_total_sales{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Sales"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "httpMethods_DELETE_requests{source=\"jwt-pizza-service\"}",
     "legendFormat": "Delete"
    },
    {
     "expr": "httpMethods_GET_requests{source=\"jwt-pizza-service\"}",
     "legendFormat": "Get"
    },
    {
     "expr": "httpMethods_POST_requests{source=\"jwt-pizza-service\"}",
     "legendFormat": "Post"
    },
    {
     "expr": "httpMethods_PUT_requests{source=\"jwt-pizza-service\"}",
     "legendFormat": "Put"
    },
    { "expr": "httpMethods_total_requests", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Creation failures/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "pizzaSales_total_failures{source=\"jwt-pizza-service\"}",
     "legendFormat": "Sales"
    }
   ]
  },
  {
   "title": "Pizza creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "pizzaSales_pizza_latency_ms{source=\"jwt-pizza-service\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "General Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "httpMethods_general_latency_ms{source=\"jwt-pizza-service\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Logs(old)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  }
 ]
}